#define JS_A KC_A
#define JS_B KC_B
#define JS_C KC_C
#define JS_D KC_D
#define JS_E KC_E
#define JS_F KC_F
#define JS_G KC_G
#define JS_H KC_H
#define JS_I KC_I
#define JS_J KC_J
#define JS_K KC_K
#define JS_L KC_L
#define JS_M KC_M
#define JS_N KC_N
#define JS_O KC_O
#define JS_P KC_P
#define JS_Q KC_Q
#define JS_R KC_R
#define JS_S KC_S
#define JS_T KC_T
#define JS_U KC_U
#define JS_V KC_V
#define JS_W KC_W
#define JS_X KC_X
#define JS_Y KC_Y
#define JS_Z KC_Z

#define JS_SCLN KC_SCLN
#define JS_SLSH KC_SLSH
#define JS_ESC KC_ESC
#define JS_CAPS KC_CAPS
#define JS_ENT KC_ENT
#define JS_BSPC KC_BSPC
#define JS_LNG1 KC_LNG1
#define JS_LNG2 KC_LNG2
#define JS_SPC KC_SPC
#define JS_TAB KC_TAB
#define JS_LALT KC_LALT
#define JS_RALT KC_RALT
#define JS_LEFT_GUI KC_LEFT_GUI
#define JS_RIGHT_GUI KC_RIGHT_GUI
#define JS_LSFT KC_LSFT
#define JS_RSFT KC_RSFT
#define JS_LCTL KC_LCTL
#define JS_RCTL KC_RCTL
#define JS_COMM KC_COMM
#define JS_DOT KC_DOT
#define JS_DEL KC_DEL
#define JS_HOME KC_HOME
#define JS_END KC_END
#define JS_LEFT KC_LEFT
#define JS_UP KC_UP
#define JS_RGHT KC_RGHT
#define JS_DOWN KC_DOWN
#define JS_PGUP KC_PGUP
#define JS_PGDN KC_PGDN
#define JS_BTN1 KC_BTN1
#define JS_BTN2 KC_BTN2
#define JS_BTN3 KC_BTN3
#define JS_BTN4 KC_BTN4
#define JS_BTN5 KC_BTN5

#define JS_LBRC KC_RBRC
#define JS_RBRC KC_BSLS
#define JS_ATMK KC_LBRC
#define JS_HIHU KC_MINS
#define JS_CLN KC_QUOT
#define JS_HAT KC_EQL


#define JS_YEN 0x89
#define JS_BSLSH 0x87

#define JS_1 KC_1
#define JS_2 KC_2
#define JS_3 KC_3
#define JS_4 KC_4
#define JS_5 KC_5
#define JS_6 KC_6
#define JS_7 KC_7
#define JS_8 KC_8
#define JS_9 KC_9
#define JS_0 KC_0

#define JS_F1 KC_F1
#define JS_F2 KC_F2
#define JS_F3 KC_F3
#define JS_F4 KC_F4
#define JS_F5 KC_F5
#define JS_F6 KC_F6
#define JS_F7 KC_F7
#define JS_F8 KC_F8
#define JS_F9 KC_F9
#define JS_F10 KC_F10
#define JS_F11 KC_F11
#define JS_F12 KC_F12